apiVersion: batch/v1
kind: Job
metadata:
  name: ecommerce-be-migrations
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
        - name: ecommerce-shop-be-migrations
          image: kristijan92/ecommerce-shop-be
          command: ["npm", "run", "migration:run:prod"]
          env:
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-host
            - name: "DB_PORT"
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-port
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user
            - name: "DB_PASS"
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-pass
            - name: "DB_DATABASE"
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-database
      restartPolicy: OnFailure
