apiVersion: batch/v1
kind: Job
metadata:
  name: ecommerce-be-migrations
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
        - name: ecommerce-shop-be-migrations
          image: kristijan92/ecommerce-shop-be:1.1.1
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-host
      restartPolicy: OnFailure
