apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: db-credentials
  data:
    - secretKey: db-name
      remoteRef:
        key: db
        property: db-name
    - secretKey: db-pass
      remoteRef:
        key: db
        property: db-pass
    - secretKey: db-user
      remoteRef:
        key: db
        property: db-user
    - secretKey: db-host
      remoteRef:
        key: db
        property: db-host
