apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-be-ingress
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ecommerce-homelab-api.projects.jovanovski.dev
      secretName: ecommerce-be-tls
  rules:
    - host: ecommerce-homelab-api.projects.jovanovski.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecommerce-be-service
                port:
                  number: 80
