apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - list:
        elements:
          - env: local
            url: https://kubernetes.default.svc
            repoURL: https://charts.external-secrets.io
            targetRevision: 1.2.1
          # - env: prod
          #   url: https://prod-cluster-url
  template:
    metadata:
      name: "{{.env}}-external-secrets"
    spec:
      project: default
      sources:
        - chart: external-secrets
          repoURL: "{{.repoURL}}"
          targetRevision: "{{.targetRevision}}"
          helm:
            releaseName: external-secrets
            valueFiles:
              - $values/argocd/appSets/platform/values/external-secrets/values.local.yaml
        - repoURL: https://github.com/KristijanJ/ecommerce-shop-gitops.git
          targetRevision: HEAD
          ref: values
      destination:
        server: "{{.url}}"
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
