apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    # Homelab only. AWS uses Secrets Manager instead of Vault.
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values: [homelab]
        values:
          repoURL: https://helm.releases.hashicorp.com
          targetRevision: 0.32.0
  template:
    metadata:
      name: "{{metadata.labels.env}}-vault"
    spec:
      project: default
      sources:
        - chart: vault
          repoURL: "{{values.repoURL}}"
          targetRevision: "{{values.targetRevision}}"
          helm:
            releaseName: vault
            valueFiles:
              - $values/argocd/appSets/platform/values/vault/values.{{metadata.labels.env}}.yaml
        - repoURL: https://github.com/KristijanJ/ecommerce-shop-gitops.git
          targetRevision: HEAD
          ref: values
      destination:
        server: "{{server}}"
        namespace: vault
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
