apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tempo-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - list:
        elements:
          - env: homelab
            url: https://kubernetes.default.svc
            repoURL: https://grafana-community.github.io/helm-charts
            targetRevision: 3.1.0
          # - env: prod
          #   url: https://prod-cluster-url
  template:
    metadata:
      name: "{{env}}-tempo"
    spec:
      project: default
      sources:
        - chart: tempo
          repoURL: "{{repoURL}}"
          targetRevision: "{{targetRevision}}"
          helm:
            releaseName: tempo
            valueFiles:
              - $values/argocd/appSets/platform/values/tempo/values.{{env}}.yaml
        - repoURL: https://github.com/KristijanJ/ecommerce-shop-gitops.git
          targetRevision: HEAD
          ref: values
      destination:
        server: "{{url}}"
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
