apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traefik-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    # Homelab only. AWS uses the AWS Load Balancer Controller instead of Traefik.
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values: [homelab]
        values:
          repoURL: https://traefik.github.io/charts
          targetRevision: 35.2.0
  template:
    metadata:
      name: "{{metadata.labels.env}}-traefik"
    spec:
      project: default
      sources:
        - chart: traefik
          repoURL: "{{values.repoURL}}"
          targetRevision: "{{values.targetRevision}}"
          helm:
            releaseName: traefik-ingress-controller
            valueFiles:
              - $values/argocd/appSets/platform/values/traefik/values.{{metadata.labels.env}}.yaml
        - repoURL: https://github.com/KristijanJ/ecommerce-shop-gitops.git
          targetRevision: HEAD
          ref: values
      destination:
        server: "{{server}}"
        namespace: traefik
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
