apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KristijanJ/ecommerce-shop-gitops.git
    targetRevision: HEAD
    path: apps/frontend/envs/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
