apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secret-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KristijanJ/ecommerce-shop-gitops.git
    targetRevision: HEAD
    path: infrastructure/vault-secret-store
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
