apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - secret-jwt.yaml
images:
  - name: kristijan92/ecommerce-shop-fe
    newTag: 1.1.6
